import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.zoho.com/people/');
  await page.getByRole('link', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Email address or mobile number' }).fill('Reshni.Suyambudurai@kanini.com');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Enter your email, phone, or' }).fill('Reshni.Suyambudurai@kanini.com');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#i0118').fill('Shree@123');
  await page.locator('#i0118').press('Enter');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('link', { name: 'I Understand' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Leave Tracker' }).locator('i').click();
  await page.getByRole('listitem', { name: 'Time Tracker' }).locator('i').click();
  await page.goto('https://myhrms.kanini.com/kanini/zp#timetracker/mydata/timelogs-mode:list');
  await page.locator('#my_logselectBtn').click();
  await page.getByText('Weekly Log').click();
  await page.locator('#ts_mydata_timelogs_bulk_view_popup').click();
  await page.locator('#bulk_log_addrow').click();
  await page.locator('#weekclientselect14-container').getByText('Select').click();
  await page.locator('#zselect-37215362-listbox-11653000019440024 > .zdropdownlist__content > .zdropdownlist__text').click();
  await page.locator('#weekprojectselect14-container > .zselectbox__icon > .zselectbox__arrow').click();
  await page.locator('#zselect-31262293-listbox-11653000035404926 > .zdropdownlist__content > .zdropdownlist__text').click();
  await page.locator('#weekjobselect14-container').getByText('Select').click();
  await page.locator('div').filter({ hasText: /^Unpaid LeaveAbsentPaid LeaveWeekendOn DutyHoliday$/ }).first().click();
  await page.locator('#weekjobselect14-container').getByText('Select').click();
  await page.locator('#zselect-68696293-listbox-11653000060460660 > .zdropdownlist__content > .zdropdownlist__text').click();
  await page.locator('#weekworkitem14').click();
  await page.locator('#weekworkitem14').fill('Testing it');
  await page.locator('#weekrow14 > td:nth-child(8) > .zpl_flexaligngap3 > #daytxt2').click();
  await page.locator('#weekrow14 > td:nth-child(8) > .zpl_flexaligngap3 > #daytxt2').fill('00:01');
  await page.getByText('SaveResetCancelUnpaid').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Leave Tracker' }).locator('i').click();
  await page.getByRole('button', { name: 'Apply Leave' }).first().click();
  await page.locator('#zp_field_11653000000036105-container').click();
  await page.getByText('Earned Leave').click();
  await page.locator('#zp_field_11653000000036109-container').getByRole('img').click();
  await page.getByRole('gridcell', { name: '15' }).click();
  await page.getByRole('textbox', { name: 'Reason for leave*' }).click();
  await page.getByRole('textbox', { name: 'Reason for leave*' }).fill('simply');
  await page.getByRole('button', { name: 'Cancel' }).click();
});