import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://accounts.zoho.in/signin?servicename=zohopeople&serviceurl=https%3A%2F%2Fmyhrms.kanini.com%2Fkanini%2Fzp#home/myspace/overview-actionlist');
  await page.getByRole('textbox', { name: 'Email address or mobile number' }).click();
  await page.getByRole('textbox', { name: 'Email address or mobile number' }).fill('Reshni.Suyamby');
  await page.getByText('Try smart sign-in STEP 1 OF 2').click();
  await page.getByRole('textbox', { name: 'Email address or mobile number' }).click();
  await page.getByRole('textbox', { name: 'Email address or mobile number' }).click();
  await page.getByRole('textbox', { name: 'Email address or mobile number' }).fill('Reshni.Suyambudurai@kanini.com');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Enter your email, phone, or' }).fill('Reshni.Suyambudurai@kanini.com');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#i0118').fill('demoo@123');
  await page.locator('#i0118').press('Enter');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.locator('#lightbox').click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.goto('https://myhrms.kanini.com/kanini/zp#home/myspace/overview-actionlist');
  await page.getByRole('listitem').filter({ hasText: 'Leave Tracker' }).locator('i').click();
  await page.getByRole('listitem', { name: 'Time Tracker' }).locator('i').click();
  await page.goto('https://myhrms.kanini.com/kanini/zp#timetracker/mydata/timelogs-mode:list');
  await page.locator('#my_logselectBtn').click();
  await page.getByText('Weekly Log').click();
  await page.locator('#weekclientselect1-container').getByText('Select').click();
  await page.locator('#weekjobselect1-container').getByText('Select').click();
  await page.locator('#zzselect-62604592-listbox-searchbox').click();
  await page.getByText('Learning & Development').click();
  await page.locator('#weekworkitem1').click();
  await page.locator('#weekworkitem1').fill('Going through angular concepts');
  await page.getByRole('row', { name: '1 Going through angular' }).locator('#daytxt2').click();
  await page.getByRole('row', { name: '1 Going through angular' }).locator('#daytxt2').fill('3');
  await page.locator('#weekjobselect2-container').getByText('Select').click();
  await page.locator('#zselect-39199233-listbox-11653000060460660').getByText('Meeting').click();
  await page.locator('#weekworkitem2').click();
  await page.locator('#weekworkitem2').fill('Daily scrum');
  await page.getByRole('row', { name: 'Daily scrum        00:00' }).locator('#daytxt2').click();
  await page.getByRole('row', { name: 'Daily scrum        00:00' }).locator('#daytxt2').fill('1');
  await page.locator('#weekclientselect3-container').getByText('Select').click();
  await page.locator('#zselect-45148773-listbox-11653000019440024').getByText('KANINI - Internal').click();
  await page.locator('#weekprojectselect3-container').click();
  await page.getByRole('option', { name: 'Organizational Activities' }).click();
  await page.locator('#weekjobselect3-container').getByText('Select').click();
  await page.locator('#zselect-74738957-listbox-11653000035404978').getByText('Learning & Development').click();
  await page.locator('#weekworkitem3').click();
  await page.locator('#weekworkitem3').fill('Reviewing Playwright automation projects spec and design.md files');
  await page.getByRole('row', { name: '3 Reviewing Playwright' }).locator('#daytxt2').click();
  await page.getByRole('row', { name: '3 Reviewing Playwright' }).locator('#daytxt2').fill('1');
  await page.getByRole('button', { name: 'Save' }).click();
});